# Generated by Django 5.1.7 on 2025-03-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(default='static/img/def_photo.jpg', upload_to='doctors/'),
        ),
    ]
