# Generated by Django 5.1.7 on 2025-03-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicApp', '0002_doctor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(default='media/img/def_photo.jpg', upload_to='doctors/'),
        ),
    ]
